export const mockEmployees: Record<string, any> = {
    'RSOT1001': {
        name: 'H.P Danindu Nadith',
        position: 'Full Stack Dev',
        team: 'Team 01',
        email: 'danindunadith2002@gmail.com',
        phone: '725253336',
        profileImage: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Colombo',
        joinDate: '2024-06-01',
        employeeId: 'RSOT1001',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT1002': {
        name: 'K.D.G Perera',
        position: 'Full Stack Dev',
        team: 'Team 01',
        email: 'kdgimhan@gmail.com',
        phone: '763412162',
        profileImage: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Moratuwa',
        joinDate: '2024-07-15',
        employeeId: 'RSOT1002',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT1003': {
        name: 'MNM Nazif',
        position: 'AI Dev',
        team: 'Team 01',
        email: 'mohamednazif2001@gmail.com',
        phone: '778521218',
        profileImage: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Peradeniya',
        joinDate: '2024-08-10',
        employeeId: 'RSOT1003',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT1004': {
        name: 'Hamdha Uwais',
        position: 'UI/UX',
        team: 'Team 01',
        email: 'hamdhauwais19@gmail.com',
        phone: '779132372',
        profileImage: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'Sri Lanka Institute of Information Technology',
        joinDate: '2024-09-01',
        employeeId: 'RSOT1004',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT1005': {
        name: 'S.V.Pradeepkumara',
        position: 'Full Stack Dev',
        team: 'Team 01',
        email: 'sithagikumara@gmail.com',
        phone: '742794103',
        profileImage: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Kelaniya',
        joinDate: '2024-06-20',
        employeeId: 'RSOT1005',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT1006': {
        name: 'K Piranavan',
        position: 'Full Stack Dev',
        team: 'Team 01',
        email: 'piranavan0594@gmail.com',
        phone: '756792519',
        profileImage: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Jaffna',
        joinDate: '2024-07-01',
        employeeId: 'RSOT1006',
        ongoingProject: 'Customer Support Ticket System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2001': {
        name: 'Mathisha Pinnaduwage',
        position: 'UI/UX',
        team: 'Team 02',
        email: 'mathishadesilva1999@gmail.com',
        phone: '712400119',
        profileImage: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Moratuwa',
        joinDate: '2024-05-15',
        employeeId: 'RSOT2001',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2002': {
        name: 'Sriwardana LWNR',
        position: 'UI/UX',
        team: 'Team 02',
        email: 'imrandika810@gmail.com',
        phone: '756863056',
        profileImage: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Colombo',
        joinDate: '2024-06-10',
        employeeId: 'RSOT2002',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2003': {
        name: 'M.K.Chandures Priyavindya',
        position: 'Full Stack Dev',
        team: 'Team 02',
        email: 'chandurespriyavindya@gmail.com',
        phone: '761934162',
        profileImage: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Peradeniya',
        joinDate: '2024-07-20',
        employeeId: 'RSOT2003',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2004': {
        name: 'Mohamed Hilmy Mohamed Ashrif',
        position: 'Full Stack Dev',
        team: 'Team 02',
        email: 'mhmashrif6141@gmail.com',
        phone: '770123668',
        profileImage: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Jaffna',
        joinDate: '2024-08-05',
        employeeId: 'RSOT2004',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2005': {
        name: 'AGF Sarah',
        position: 'AI Dev',
        team: 'Team 02',
        email: 'fathimasarahgaffar@gmail.com',
        phone: '769443397',
        profileImage: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'Sri Ascent University',
        joinDate: '2024-06-25',
        employeeId: 'RSOT2005',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT2006': {
        name: 'Raviprabha Sanduni Jayalal',
        position: 'Full Stack Dev',
        team: 'Team 02',
        email: 'sanduniraviprabha@gmail.com',
        phone: '786906224',
        profileImage: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Ruhuna',
        joinDate: '2024-07-10',
        employeeId: 'RSOT2006',
        ongoingProject: 'Energy Consumption Monitoring System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3001': {
        name: 'Isuru Nayanajith',
        position: 'UI/UX',
        team: 'Team 03',
        email: 'isurunayanajith50@gmail.com',
        phone: '763360993',
        profileImage: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Moratuwa',
        joinDate: '2024-05-01',
        employeeId: 'RSOT3001',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3002': {
        name: 'M.S.M. Shamaz',
        position: 'UI/UX',
        team: 'Team 03',
        email: 'mohammedshamaz51@gmail.com',
        phone: '764788285',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Colombo',
        joinDate: '2024-06-15',
        employeeId: 'RSOT3002',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3003': {
        name: 'A.M.Mohamed Raheethus Alfer',
        position: 'Full Stack Dev',
        team: 'Team 03',
        email: 'ammralfer@gmail.com',
        phone: '762783047',
        profileImage: 'https://images.pexels.com/photos/937626/pexels-photo-937626.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Peradeniya',
        joinDate: '2024-07-01',
        employeeId: 'RSOT3003',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3004': {
        name: 'I.K.Nipun Buddhima',
        position: 'Full Stack Dev',
        team: 'Team 03',
        emons: 'nipunbuddhima999@gmail.com',
        phone: '716627996',
        profileImage: 'https://images.pexels.com/photos/1081685/pexels-photo-1081685.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Kelaniya',
        joinDate: '2024-08-01',
        employeeId: 'RSOT3004',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3005': {
        name: 'Praveen Jeyachandran',
        position: 'AI Dev',
        team: 'Team 03',
        email: 'jeyachandranpraveen2002@gmail.com',
        phone: '771230145',
        profileImage: 'https://images.pexels.com/photos/1080213/pexels-photo-1080213.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Jaffna',
        joinDate: '2024-06-20',
        employeeId: 'RSOT3005',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3006': {
        name: 'A.P.D.Tamasha',
        position: 'AI Dev',
        team: 'Team 03',
        email: 'tamashaabesuriya@gmail.com',
        phone: '703636491',
        profileImage: 'https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Moratuwa',
        joinDate: '2024-07-15',
        employeeId: 'RSOT3006',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT3007': {
        name: 'Renal Perera',
        position: 'Full Stack Dev',
        team: 'Team 03',
        email: 'renalperera15@gmail.com',
        phone: '761868387',
        profileImage: 'https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Colombo',
        joinDate: '2024-08-10',
        employeeId: 'RSOT3007',
        ongoingProject: 'Quality Control Dashboard',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT4001': {
        name: 'M.R.F.Nusrath Nuha',
        position: 'AI Dev',
        team: 'Team 04',
        email: 'nusrathnuha7@gmail.com',
        phone: '773463538',
        profileImage: 'https://images.pexels.com/photos/415071/pexels-photo-415071.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Peradeniya',
        joinDate: '2024-05-10',
        employeeId: 'RSOT4001',
        ongoingProject: 'Waste Management System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT4002': {
        name: 'T. D. Godawattage',
        position: 'AI Dev',
        team: 'Team 04',
        email: 'thirasaradewmin@gmail.com',
        phone: '717667161',
        profileImage: 'https://images.pexels.com/photos/1081683/pexels-photo-1081683.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Moratuwa',
        joinDate: '2024-06-05',
        employeeId: 'RSOT4002',
        ongoingProject: 'Waste Management System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT4003': {
        name: 'J.A.P.P Madhawa',
        position: 'UI/UX',
        team: 'Team 04',
        email: 'praveenmadhawa999@gmail.com',
        phone: '714661123',
        profileImage: 'https://images.pexels.com/photos/943084/pexels-photo-943084.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Colombo',
        joinDate: '2024-07-01',
        employeeId: 'RSOT4003',
        ongoingProject: 'Waste Management System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT4004': {
        name: 'W A S D Weerakkodi',
        position: 'Full Stack Dev',
        team: 'Team 04',
        email: 'pasachiya@gmail.com',
        phone: '787586563',
        profileImage: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Ruhuna',
        joinDate: '2024-08-15',
        employeeId: 'RSOT4004',
        ongoingProject: 'Waste Management System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
    'RSOT4005': {
        name: 'C.Ishara Sewwandi',
        position: 'Full Stack Dev',
        team: 'Team 04',
        email: 'ishasewwandi26@gmail.com',
        phone: '765694766',
        profileImage: 'https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg?auto=compress&cs=tinysrgb&w=400',
        university: 'University of Kelaniya',
        joinDate: '2024-06-25',
        employeeId: 'RSOT4005',
        ongoingProject: 'Waste Management System',
        previousProjects: 'None',
        previousTeam: 'None',
        status: 'Activate',
    },
};