export const mockEmployees: Record<string, any> = {
    'EMP001': {
        name: 'H.P Danindu Nadith',
        position: 'Full Stack Dev',
        team: 'Team Blue',
        email: 'danindunadith2002@gmail.com',
        phone: '0725253336',
        profileImage: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Software Development',
        university: '',
        joinDate: '2025-05-02',
        employeeId: 'RSOT1001',
        ongoingProject: 'HR - ERP',
        previousProjects: 'Customer Support Ticket System',
        previousTeam: 'Team 01',
    },
    'EMP002': {
        name: 'Sarah Johnson',
        position: 'Product Manager',
        team: 'Product Team',
        email: 'sarah.johnson@techcorp.com',
        phone: '+1 (555) 234-5678',
        profileImage: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Product',
        location: 'San Francisco Office',
        joinDate: '2021-08-20',
        employeeId: 'EMP002',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
    'EMP003': {
        name: 'Michael Chen',
        position: 'UI/UX Designer',
        team: 'Design Team',
        email: 'michael.chen@techcorp.com',
        phone: '+1 (555) 345-6789',
        profileImage: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400',
        department: 'Design',
        location: 'Los Angeles Office',
        joinDate: '2023-01-10',
        employeeId: 'EMP003',
    },
};